[package]
name = "calr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
chrono = "0.4"
clap = "2.33"
itertools = "0.10"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
